services:
  db:
    container_name: bat_db
    image: postgres
    ports:
      - "5432:5432"
    restart: no
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  spring-app:
      container_name: bat_app
      image: mechimaru/batcomputer-app:v1
      ports:
        - "8080:8080"
      restart: no
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_URL: ${POSTGRES_URL}
      depends_on:
        db:
          condition: service_healthy